// Package workload verifies short-lived X.509 workload certificates
// (I05 Phase 0: SPIFFE URI SAN spiffe://saoaf.test/ns/default/sa/<name>,
// generated by mocks/identity/workload/generate-test-svid.sh). Production
// swaps the trust bundle source only.
package workload

import (
	"crypto/x509"
	"errors"
	"fmt"
	"net/url"
	"strings"
)

// ErrRejected is the coarse mTLS failure; details log-only.
var ErrRejected = errors.New("workload certificate rejected")

// AllowedSAN is the Phase 0 trust-domain prefix.
const AllowedSAN = "spiffe://saoaf.test/"

// Verifier validates client certificates against a trust bundle.
type Verifier struct {
	roots       *x509.CertPool
	trustDomain string
}

// NewVerifier builds a Verifier from PEM CA certificates and the allowed
// SPIFFE trust domain ("" defaults to AllowedSAN).
func NewVerifier(rootsPEM []byte, trustDomain string) (*Verifier, error) {
	pool := x509.NewCertPool()
	if len(rootsPEM) > 0 && !pool.AppendCertsFromPEM(rootsPEM) {
		return nil, errors.New("workload: no usable CA certificates in bundle")
	}
	if trustDomain == "" {
		trustDomain = AllowedSAN
	}
	if !strings.HasSuffix(trustDomain, "/") {
		trustDomain += "/"
	}
	return &Verifier{roots: pool, trustDomain: trustDomain}, nil
}

// Chain holds the leaf and intermediates presented by a client.
type Chain struct {
	Leaf          *x509.Certificate
	Intermediates []*x509.Certificate
}

// Verify checks signature chain, expiry, and the SPIFFE URI SAN trust
// domain. Failures return ErrRejected with no certificate internals.
func (v *Verifier) Verify(chain Chain) error {
	if chain.Leaf == nil {
		return fmt.Errorf("%w: no certificate", ErrRejected)
	}
	if _, err := chain.Leaf.Verify(x509.VerifyOptions{
		Roots:         v.roots,
		Intermediates: intermediatesPool(chain.Intermediates),
		KeyUsages:     []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
	}); err != nil {
		return fmt.Errorf("%w: chain invalid", ErrRejected)
	}
	san, err := SPIFFESAN(chain.Leaf)
	if err != nil {
		return err
	}
	if !strings.HasPrefix(san, v.trustDomain) {
		return fmt.Errorf("%w: untrusted SPIFFE domain", ErrRejected)
	}
	return nil
}

// SPIFFESAN extracts the spiffe:// URI SAN from a certificate.
func SPIFFESAN(cert *x509.Certificate) (string, error) {
	for _, u := range cert.URIs {
		if u != nil && u.Scheme == "spiffe" {
			return u.String(), nil
		}
	}
	return "", fmt.Errorf("%w: no SPIFFE URI SAN", ErrRejected)
}

// SANWorkloadID returns the workload id (path after trust domain) of the
// SPIFFE SAN, e.g. resource-resolver.
func SANWorkloadID(cert *x509.Certificate) (string, error) {
	san, err := SPIFFESAN(cert)
	if err != nil {
		return "", err
	}
	u, err := url.Parse(san)
	if err != nil {
		return "", fmt.Errorf("%w: bad SAN uri", ErrRejected)
	}
	return strings.TrimPrefix(u.Path, "/ns/"), nil
}

func intermediatesPool(certs []*x509.Certificate) *x509.CertPool {
	if len(certs) == 0 {
		return nil
	}
	pool := x509.NewCertPool()
	for _, c := range certs {
		pool.AddCert(c)
	}
	return pool
}
