const copy = {
  en: {
    skip: "Skip to content", navArchitecture: "Architecture", navStart: "Get started", navStandards: "Standards", navContribute: "Contribute", eyebrow: "OPEN REFERENCE ARCHITECTURE · PRE-RELEASE",
    heroTitle: "Sovereign AI<br />&amp; Open AI Fabric", heroLede: "A practical architecture for enterprises that need to choose, connect, govern, replace, and prove control over AI capabilities.", heroPrimary: "Read the implementation guide", heroSecondary: "Explore the modules <span aria-hidden=\"true\">↓</span>",
    factOneLabel: "Control plane", factOne: "One policy, registry, and evidence fabric", factTwoLabel: "Data planes", factTwo: "Independent model, tool, agent, and compute paths", factThreeLabel: "Principle", factThree: "Open contracts; replaceable providers",
    mapCaption: "03 / SOVEREIGN CONTROL PLANE", coreKicker: "UNIFIED CONTROL", coreTitle: "Sovereignty<br />Control Plane", coreDetail: "Policy · Registry · Resolver · Evidence", moduleModel: "Model Fabric", moduleTool: "Tool &amp; Data / MCP", moduleAgent: "Agent Federation / A2A", modulePlace: "Placement &amp; Portability",
    principlesTag: "THE OPERATING IDEA", principlesTitle: "Sovereignty is the ability to change without losing control.", p1Title: "Choose", p1Body: "Use logical capabilities, rather than hard-coded models, tools, agents, clouds, or endpoints.", p2Title: "Connect", p2Body: "Use MCP, A2A, OpenAPI, CloudEvents, OCI, and OpenTelemetry where each protocol belongs.", p3Title: "Control", p3Body: "Keep policy, identity, delegated authority, evidence, and lifecycle decisions explicit.", p4Title: "Replace", p4Body: "Prove that a provider, agent, tool, or deployment zone can be changed through tested contracts.",
    architectureTag: "ARCHITECTURE", architectureTitle: "One control plane. Four independent execution fabrics.", architectureBody: "This phase implements the Resource Router and Sovereignty Operations, integrates the existing Model Fabric, and freezes contracts for the other execution fabrics.", controlPlane: "SOVEREIGN CONTROL PLANE", controlPlaneDetail: "No model prompts, tool parameters, or business payloads", dataPlane: "SPECIALIST EXECUTION FABRICS", dataPlaneDetail: "Independently deployed, scaled, and operated", governanceTitle: "Governance &amp; Policy", governanceBody: "Minimum policy capability required by this delivery", registryTitle: "Capability Registry &amp; Hub", registryBody: "Minimum registry capability required by this delivery", resolverTitle: "AI Resource Router", resolverBody: "Implemented in this delivery: deterministic Resource Plans", opsTitle: "Operations &amp; Exit Assurance", opsBody: "Implemented: evidence, metrics, exit packs, and drills", modelTitle: "Model Fabric", modelBody: "Existing Multi-Model Router; integrated through published contracts.", toolTitle: "Tool &amp; Data Access", toolBody: "Contract defined; runtime implementation deferred.", agentTitle: "Agent Federation", agentBody: "Contract defined; runtime implementation deferred.", placementTitle: "Placement &amp; Portability", placementBody: "Contract defined; runtime implementation deferred.", boundaryNote: "<strong>Boundary:</strong> the Resource Router does not choose a concrete model, execute a tool, orchestrate an agent, retrieve context, authorize an action, or schedule infrastructure.",
    flowTag: "RUNTIME FLOW", flowTitle: "Plan centrally. Execute directly.", flow1Title: "Declare capabilities", flow1Body: "An Agent Harness sends structured requirements and sovereignty constraints.", flow2Title: "Resolve a plan", flow2Body: "The Resource Router returns providers, profiles/actions, contract versions, and a short-lived plan ID.", flow3Title: "Call direct data planes", flow3Body: "The Harness invokes MMR, Context, MCP, or A2A endpoints directly.", flow4Title: "Link evidence", flow4Body: "Model route, tool execution, agent task, and policy decision IDs remain traceable without copying payloads.",
    startTag: "GET STARTED", startTitle: "Start with one narrow, verifiable capability path.", startBody: "The first production slice should be small enough to audit and meaningful enough to prove replacement and governance.", start1Title: "Publish a capability", start1Body: "Define a stable capability ID, owner, risk level, data classification, and contract version.", start2Title: "Register a provider", start2Body: "Publish a signed logical profile or action snapshot. Do not expose credentials or internal instances.", start3Title: "Bind and resolve", start3Body: "Create an environment-specific binding. Resolve it into a short-lived Resource Plan at runtime.", start4Title: "Run an exit drill", start4Body: "Switch to an alternate provider and verify the same capability works with the same Agent contract.",
    standardsTag: "OPEN CONTRACTS", standardsTitle: "Use each standard for its native job.", standardsBody: "Interoperability improves when protocols are composed instead of being forced through a single private abstraction.", stdHeadStandard: "Standard", stdHeadRole: "Role in the fabric", stdHeadOwner: "Operational owner", stdMcpRole: "Tools and data service connectivity", stdMcpOwner: "Tool &amp; Data Access Fabric", stdA2aRole: "Agent-to-agent discovery and delegation", stdA2aOwner: "Agent Federation Fabric", stdApiRole: "Synchronous contracts and enterprise adapters", stdApiOwner: "Control Plane &amp; domain teams", stdEventsRole: "Configuration and lifecycle change notifications", stdEventsOwner: "All modules", stdOtelRole: "Trace context, metrics, logs, and evidence links", stdOtelOwner: "Operations &amp; Exit Assurance", stdOciRole: "Portable artifacts and deployment manifests", stdOciOwner: "Placement &amp; AI Factory",
    governanceTag: "GOVERNANCE", governanceTitleLarge: "Open protocols do not replace accountable control.", gov1: "Identity &amp; Trust makes authentication, authorization, delegation, and approval decisions.", gov2: "The Resource Router carries constraints; specialist gateways enforce decisions at execution time.", gov3: "The control plane stores metadata and evidence references, never prompts, tool parameters, credentials, or model responses.", gov4: "Every critical provider needs an owner, contract, lifecycle, and tested exit path.",
    contributeTag: "CONTRIBUTE", contributeTitle: "Help make enterprise AI portable by design.", contrib1Title: "Architecture", contrib1Body: "Propose a boundary, ADR, threat model, or reference deployment that preserves domain authority.", contrib2Title: "Contracts", contrib2Body: "Add capability schemas, provider snapshots, compatibility fixtures, or protocol conformance tests.", contrib3Title: "Adapters", contrib3Body: "Build thin, replaceable adapters for MMR, MCP, A2A, Context, and AI Factory integrations.", contributeCallout: "This reference is pre-release. Begin by reading the architecture, opening a scoped proposal, and validating the hardest integration with a proof of concept.", contributeButton: "Start with the guide", footer: "Sovereign AI &amp; Open AI Fabric · Open reference architecture for enterprise AI.", backTop: "Back to top ↑"
  },
  zh: {
    skip: "跳到正文", navArchitecture: "架构", navStart: "快速开始", navStandards: "开放标准", navContribute: "参与贡献", eyebrow: "开放参考架构 · 预发布",
    heroTitle: "Sovereign AI<br />&amp; Open AI Fabric", heroLede: "面向企业的可落地参考架构：让企业持续拥有选择、连接、治理、替换和证明 AI 控制权的能力。", heroPrimary: "阅读实施指南", heroSecondary: "查看模块 <span aria-hidden=\"true\">↓</span>",
    factOneLabel: "控制面", factOne: "统一政策、目录与证据织网", factTwoLabel: "数据面", factTwo: "模型、工具、Agent、算力独立运行", factThreeLabel: "原则", factThree: "开放契约；Provider 可替换",
    mapCaption: "03 / 主权控制面", coreKicker: "统一控制", coreTitle: "Sovereignty<br />Control Plane", coreDetail: "Policy · Registry · Resolver · Evidence", moduleModel: "模型织网", moduleTool: "工具与数据 / MCP", moduleAgent: "Agent 联邦 / A2A", modulePlace: "放置与可移植性",
    principlesTag: "核心理念", principlesTitle: "主权，是在变化发生时仍不失去控制的能力。", p1Title: "选择", p1Body: "用逻辑能力替代硬编码模型、工具、Agent、云和端点。", p2Title: "连接", p2Body: "让 MCP、A2A、OpenAPI、CloudEvents、OCI 与 OpenTelemetry 各司其职。", p3Title: "控制", p3Body: "让政策、身份、委派、证据和生命周期决策始终明确可查。", p4Title: "替换", p4Body: "用经过验证的契约证明 Provider、Agent、工具和部署区可被替换。",
    architectureTag: "总体架构", architectureTitle: "一个控制面，四类独立执行织网。", architectureBody: "本期实现 Resource Router 与主权运营，集成既有模型织网，并冻结其他执行织网的接口契约。", controlPlane: "主权控制面", controlPlaneDetail: "不存放模型 Prompt、工具参数或业务载荷", dataPlane: "专业执行织网", dataPlaneDetail: "独立部署、扩缩容和运维", governanceTitle: "治理与政策", governanceBody: "实现本期交付所需的最小政策能力", registryTitle: "能力目录与 Resource Hub", registryBody: "实现本期交付所需的最小目录能力", resolverTitle: "AI Resource Router", resolverBody: "本期实现：确定性生成 Resource Plan", opsTitle: "运营与退出保证", opsBody: "本期实现：证据、指标、退出包与演练", modelTitle: "模型织网", modelBody: "Multi-Model Router 已实现，本期按既有契约集成。", toolTitle: "工具与数据接入", toolBody: "仅定义接口，本期暂缓运行时实现。", agentTitle: "Agent 联邦", agentBody: "仅定义接口，本期暂缓运行时实现。", placementTitle: "放置与可移植性", placementBody: "仅定义接口，本期暂缓运行时实现。", boundaryNote: "<strong>边界：</strong>Resource Router 不选择具体模型，不执行工具，不编排 Agent，不检索 Context，不裁决授权，也不调度基础设施。",
    flowTag: "运行时链路", flowTitle: "集中生成计划，直连专业数据面执行。", flow1Title: "声明能力需求", flow1Body: "Agent Harness 提交结构化能力需求和主权约束。", flow2Title: "解析资源计划", flow2Body: "Resource Router 返回 Provider、profile/action、契约版本和短期 Plan ID。", flow3Title: "直连专业数据面", flow3Body: "Harness 直接调用 MMR、Context、MCP 或 A2A 端点。", flow4Title: "关联执行证据", flow4Body: "模型路由、工具执行、Agent 任务和授权决定 ID 可追溯，但不复制业务载荷。",
    startTag: "快速开始", startTitle: "先从一条窄而可验证的能力路径开始。", startBody: "首个生产闭环应足够小，能够审计；也足够真实，能够证明替换与治理能力。", start1Title: "发布能力", start1Body: "定义稳定的 Capability ID、Owner、风险等级、数据级别和契约版本。", start2Title: "注册 Provider", start2Body: "发布已签名的逻辑 profile 或 action Snapshot，不暴露凭证和内部实例。", start3Title: "建立 Binding 并解析", start3Body: "创建环境专属 Binding，在运行时解析为短期 Resource Plan。", start4Title: "执行退出演练", start4Body: "切换到替代 Provider，验证相同 Agent 契约下能力仍可运行。",
    standardsTag: "开放契约", standardsTitle: "让每个标准做它原生擅长的事。", standardsBody: "把协议组合起来，而不是强行塞进一个私有抽象，才能获得真正的互操作性。", stdHeadStandard: "标准", stdHeadRole: "在织网中的职责", stdHeadOwner: "运行 Owner", stdMcpRole: "工具与数据服务连接", stdMcpOwner: "工具与数据接入织网", stdA2aRole: "Agent 间发现与委派", stdA2aOwner: "Agent 联邦织网", stdApiRole: "同步契约与企业适配", stdApiOwner: "控制面与领域团队", stdEventsRole: "配置与生命周期变化通知", stdEventsOwner: "全部模块", stdOtelRole: "追踪上下文、指标、日志和证据关联", stdOtelOwner: "运营与退出保证", stdOciRole: "可移植制品与部署清单", stdOciOwner: "放置织网与 AI Factory",
    governanceTag: "治理", governanceTitleLarge: "开放协议不等于没有责任主体。", gov1: "Identity &amp; Trust 工程裁决认证、授权、委派和审批。", gov2: "Resource Router 传递约束；专业 Gateway 在执行点强制执行决定。", gov3: "控制面只保存元数据和证据引用，绝不保存 Prompt、工具参数、凭证或模型响应。", gov4: "每个关键 Provider 都要有 Owner、契约、生命周期和经过验证的退出路径。",
    contributeTag: "参与贡献", contributeTitle: "帮助企业 AI 从架构开始就具备可移植性。", contrib1Title: "架构", contrib1Body: "贡献边界、ADR、威胁模型或能够保持领域权威的参考部署。", contrib2Title: "契约", contrib2Body: "贡献 Capability Schema、Provider Snapshot、兼容性样例或协议一致性测试。", contrib3Title: "适配器", contrib3Body: "为 MMR、MCP、A2A、Context 和 AI Factory 构建薄而可替换的适配器。", contributeCallout: "本参考架构仍处于预发布阶段。请先阅读架构说明，提出范围明确的提案，并用 PoC 验证最难的集成。", contributeButton: "从指南开始", footer: "Sovereign AI &amp; Open AI Fabric · 面向企业 AI 的开放参考架构。", backTop: "返回顶部 ↑"
  }
};

const button = document.querySelector('.language-switch');
let language = 'en';

function render(lang) {
  language = lang;
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const value = copy[lang][element.dataset.i18n];
    if (value) element.innerHTML = value;
  });
  button.setAttribute('aria-pressed', String(lang === 'zh'));
  button.querySelector('.language-label').textContent = lang === 'zh' ? 'EN' : '中文';
  button.setAttribute('aria-label', lang === 'zh' ? 'Switch to English' : '切换到中文');
  document.title = lang === 'zh' ? 'Sovereign AI & Open AI Fabric｜开放参考架构' : 'Sovereign AI & Open AI Fabric';
}

button.addEventListener('click', () => render(language === 'en' ? 'zh' : 'en'));
